# Generated by Django 5.1.7 on 2025-03-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_book_slug_remove_catagoery_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=255),
        ),
        migrations.AddField(
            model_name='catagoery',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=100),
        ),
    ]
