# Generated by Django 5.1.7 on 2025-03-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_slug_catagoery_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='catagoery',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
