# Generated by Django 5.1.7 on 2025-03-23 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_book_slug_alter_catagoery_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='catagory',
            new_name='catagoery',
        ),
    ]
