# Generated by Django 5.1.7 on 2025-03-23 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_catagory_book_catagoery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagoery',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='catagoery',
            new_name='category',
        ),
    ]
