# Generated by Django 5.2.1 on 2025-05-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_book_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
